import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('inject-config: missing SUPABASE_URL or SUPABASE_ANON_KEY');
  process.exit(1);
}

const out = `// Auto-generated by scripts/inject-config.mjs — do not commit secrets elsewhere.
export const supabaseUrl = ${JSON.stringify(url)};
export const supabaseAnonKey = ${JSON.stringify(key)};
`;

writeFileSync(join(root, 'js', 'config.local.js'), out, 'utf8');
console.log('inject-config: wrote js/config.local.js');
